import { Link } from 'react-router-dom'; import { Property,Section,SitePayload } from '../types'; import BookingSearch from './BookingSearch';
function propertyImage(p:Property){return Array.isArray(p.images)?p.images[0]:''}
export default function SectionRenderer({section,site}:{section:Section;site:SitePayload}){const s=section.settings;if(section.type==='hero')return <section className="hero" style={{backgroundImage:`linear-gradient(105deg,rgba(4,31,51,.88),rgba(15,61,95,.20)),url(${s.backgroundImage})`}}><div className="container hero-inner"><div><span className="eyebrow">{s.eyebrow}</span><h1>{s.heading}</h1><p>{s.description}</p><div className="hero-actions"><Link className="btn gold" to={s.primaryCta?.href??'/booking'}>{s.primaryCta?.label??'Book Now'}</Link><Link className="btn secondary" to={s.secondaryCta?.href??'/hotels'}>{s.secondaryCta?.label??'Explore Hotels'}</Link></div></div><BookingSearch properties={site.properties}/></div></section>;
if(section.type==='booking-search')return <section className="section soft"><div className="container narrow"><BookingSearch properties={site.properties} title={s.title}/></div></section>;
if(section.type==='feature-grid')return <section className="section"><div className="container"><div className="section-head"><div><div className="kicker">Hotel OS</div><h2>{s.heading}</h2></div><p>Public booking and internal hotel operations are connected, but protected by separate permissions.</p></div><div className="cards">{(s.items??[]).map((x:any,i:number)=><article className="card feature" key={x.title}><div className="card-body"><div className="num">{i+1}</div><h3>{x.title}</h3><p>{x.text}</p></div></article>)}</div></div></section>;
if(section.type==='featured-properties')return <section className="section soft"><div className="container"><div className="section-head"><div><div className="kicker">Featured Hotels</div><h2>{s.heading}</h2></div><Link className="btn secondary" to="/hotels">View All Hotels</Link></div><div className="cards">{site.properties.map(p=><article className="card" key={p.id}><div className="card-img"><img src={propertyImage(p)} alt={p.name}/></div><div className="card-body"><div className="tag-row"><span className="tag gold">{p.destination}</span><span className="tag">Direct booking</span></div><h3>{p.name}</h3><p>{p.description}</p><Link className="btn secondary" to={`/hotels/${p.slug}`}>View Hotel</Link></div></article>)}</div></div></section>;
if(section.type==='offers')return <section className="section"><div className="container"><div className="section-head"><div><div className="kicker">Offers</div><h2>{s.heading??'Special Offers'}</h2></div></div><div className="cards">{site.offers.map(o=><article className="card" key={o.id}><div className="card-img"><img src={o.imageUrl||'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80'} alt={o.title}/></div><div className="card-body"><h3>{o.title}</h3><p>{o.description}</p>{o.promoCode&&<span className="tag gold">{o.promoCode}</span>}<br/><Link className="btn secondary" to={`/offers/${o.slug}`}>View Offer</Link></div></article>)}</div></div></section>;
if(section.type==='rooms')return <section className="section"><div className="container"><div className="section-head"><div><div className="kicker">Rooms</div><h2>{s.heading??'Featured Rooms'}</h2></div></div><div className="cards">{site.properties.flatMap(p=>p.roomTypes.map(r=>({p,r}))).slice(0,6).map(({p,r})=><article className="card" key={r.id}><div className="card-img"><img src={Array.isArray(r.images)?r.images[0]:''} alt={r.name}/></div><div className="card-body"><span className="tag gold">{p.name}</span><h3>{r.name}</h3><p>{r.description}</p><Link className="btn secondary" to={`/hotels/${p.slug}/rooms/${r.slug}`}>View Room</Link></div></article>)}</div></div></section>;
if(section.type==='gallery')return <section className="section" id="gallery"><div className="container"><div className="section-head"><div><div className="kicker">Gallery</div><h2>{s.heading}</h2></div></div><div className="gallery">{(s.images??[]).slice(0,5).map((u:string,i:number)=><img key={u+i} src={u} alt={`RainWood experience ${i+1}`}/>)}</div></div></section>;
if(section.type==='contact')return <section className="section soft" id="contact"><div className="container split"><div><div className="kicker">Contact</div><h2>{s.heading}</h2><p>Our reservation team can help with direct, group, agent, company and special-stay enquiries.</p></div><div className="panel"><p><strong>Email:</strong> {s.email}</p><p><strong>Phone:</strong> {s.phone}</p><Link className="btn" to="/booking">Check Availability</Link></div></div></section>;
return null}
