import { PrismaClient } from '@prisma/client'; import bcrypt from 'bcryptjs'; const p=new PrismaClient();
const images={aurum:['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=900&q=80'],spices:['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80']};
async function main(){
 const tenant=await p.tenant.upsert({where:{slug:'rainwood'},update:{},create:{name:'RainWood Hotels',slug:'rainwood'}});
 const adminEmail=process.env.SEED_ADMIN_EMAIL ?? 'admin@rainwood.local';
 const adminPassword=process.env.SEED_ADMIN_PASSWORD;
 if(!adminPassword) throw new Error('SEED_ADMIN_PASSWORD must be set before running the seed');
 const passwordHash=await bcrypt.hash(adminPassword,12); await p.user.upsert({where:{tenantId_email:{tenantId:tenant.id,email:adminEmail}},update:{},create:{tenantId:tenant.id,email:adminEmail,passwordHash,name:'RainWood Admin',role:'TENANT_ADMIN'}});
 const aurum=await p.property.upsert({where:{tenantId_slug:{tenantId:tenant.id,slug:'rainwood-aurum-munnar'}},update:{},create:{tenantId:tenant.id,name:'RainWood Aurum',slug:'rainwood-aurum-munnar',destination:'Munnar',description:'Premium mountain stay with direct booking enabled.',address:'Munnar, Kerala',contactEmail:'reservations@rainwoodhotels.com',phone:'+91 90000 00000',taxPercentage:18,images:images.aurum,amenities:['Free Wi-Fi','Restaurant','Hill View','Family Rooms','Parking']}});
 const spices=await p.property.upsert({where:{tenantId_slug:{tenantId:tenant.id,slug:'spices-lap-resort'}},update:{},create:{tenantId:tenant.id,name:'Spices Lap Resort',slug:'spices-lap-resort',destination:'Thekkady',description:'Resort room availability with restriction-aware display.',address:'Thekkady, Kerala',contactEmail:'reservations@rainwoodhotels.com',phone:'+91 90000 00001',taxPercentage:18,images:images.spices,amenities:['Pool','Restaurant','Nature View']}});
 const room=await p.roomType.upsert({where:{propertyId_slug:{propertyId:aurum.id,slug:'premium-valley-room'}},update:{},create:{tenantId:tenant.id,propertyId:aurum.id,name:'Premium Valley Room',slug:'premium-valley-room',description:'Valley-view premium room.',maxAdults:3,maxChildren:2,maxOccupancy:4,baseOccupancy:2,inventoryCount:8,images:[images.aurum[1]],amenities:['Breakfast','Wi-Fi','Valley View']}});
 const plan=await p.ratePlan.upsert({where:{roomTypeId_code:{roomTypeId:room.id,code:'CP'}},update:{},create:{tenantId:tenant.id,propertyId:aurum.id,roomTypeId:room.id,code:'CP',name:'Breakfast Included',mealPlan:'CP',baseRate:6800,cancellationPolicy:{freeCancellationHours:72}}});
 for(let i=0;i<120;i++){const d=new Date();d.setUTCHours(0,0,0,0);d.setUTCDate(d.getUTCDate()+i);await p.inventoryDay.upsert({where:{ratePlanId_date:{ratePlanId:plan.id,date:d}},update:{},create:{tenantId:tenant.id,propertyId:aurum.id,roomTypeId:room.id,ratePlanId:plan.id,date:d,availableRooms:8,rate:i%6===0?7600:6800,minLengthOfStay:1,source:'AXISROOMS'}})}
 const themeConfig={name:'RainWood Heritage',colors:{navy:'#0f3d5f',navy2:'#184f78',gold:'#c99b42',ink:'#172333',soft:'#f5f8fb'},fonts:{heading:'Inter',body:'Inter'},buttonStyle:'pill',cardRadius:22,logoUrl:'https://rainwoodhotels.com/wp-content/webp-express/webp-images/uploads/2023/09/rwh-logo.png.webp'};
 const theme=await p.siteTheme.upsert({where:{tenantId_key:{tenantId:tenant.id,key:'rainwood-heritage'}},update:{config:themeConfig,active:true},create:{tenantId:tenant.id,name:'RainWood Heritage',key:'rainwood-heritage',config:themeConfig,active:true}});
 const sections=[
  {id:'hero',type:'hero',settings:{eyebrow:'Discover RainWood',heading:'Memorable stays across Kerala',description:'Book directly with RainWood Hotels for the best available experience.',backgroundImage:'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1600&q=80',primaryCta:{label:'Book Now',href:'/booking'},secondaryCta:{label:'Explore Hotels',href:'/hotels'}}},
  {id:'booking',type:'booking-search',settings:{title:'Search RainWood Stays',layout:'card',showPropertySelector:true,showPromoCode:true}},
  {id:'features',type:'feature-grid',settings:{heading:'Direct booking with complete reservation support',items:[{title:'Website Booking',text:'Search, select rooms and receive confirmation.'},{title:'Reservation Management',text:'Direct, agent, company, OTA, phone and WhatsApp bookings.'},{title:'Payment Workflow',text:'Online and offline payment tracking.'},{title:'Reports',text:'Arrivals, room nights, revenue and balances.'},{title:'Admin Dashboard',text:'Reservations, vouchers and operational visibility.'},{title:'AxisRooms Sync',text:'Inventory, rates, restrictions and booking push.'}]}},
  {id:'properties',type:'featured-properties',settings:{heading:'Featured Hotels',propertyIds:[aurum.id,spices.id],showStartingPrice:true}},
  {id:'gallery',type:'gallery',settings:{heading:'Experience RainWood',images:[...images.aurum,...images.spices]}},
  {id:'contact',type:'contact',settings:{heading:'Plan your RainWood stay',email:'reservations@rainwoodhotels.com',phone:'+91 90000 00000'}}
 ];
 await p.sitePage.upsert({where:{tenantId_slug:{tenantId:tenant.id,slug:'home'}},update:{themeId:theme.id,draftContent:{sections},publishedContent:{sections},status:'PUBLISHED'},create:{tenantId:tenant.id,themeId:theme.id,title:'Home',slug:'home',status:'PUBLISHED',draftContent:{sections},publishedContent:{sections},seo:{title:'RainWood Hotels',description:'Book RainWood hotels directly.'},navigation:[{label:'Home',href:'/'},{label:'Hotels',href:'/hotels'},{label:'Booking',href:'/booking'}],publishedAt:new Date()}});
 const offer=await p.offer.upsert({where:{tenantId_slug:{tenantId:tenant.id,slug:'stay-longer-save-more'}},update:{},create:{tenantId:tenant.id,propertyId:aurum.id,title:'Stay Longer, Save More',slug:'stay-longer-save-more',description:'Save on stays of three nights or longer.',imageUrl:'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',discountType:'PERCENT',discountValue:10,promoCode:'RAIN10',blackoutDates:[],terms:['Subject to availability'],active:true}});
 const standardPages=[
  {title:'Offers',slug:'offers',sections:[{id:'offers-list',type:'offers',settings:{heading:'Book direct and enjoy more',offerIds:[offer.id],showPromoCode:true}}]},
  {title:'Gallery',slug:'gallery',sections:[{id:'gallery-main',type:'gallery',settings:{heading:'Experience RainWood',images:[...images.aurum,...images.spices]}}]},
  {title:'Contact',slug:'contact',sections:[{id:'contact-main',type:'contact',settings:{heading:'Plan your RainWood stay',email:'reservations@rainwoodhotels.com',phone:'+91 90000 00000'}}]},
  {title:'Rooms',slug:'rooms',sections:[{id:'rooms-main',type:'rooms',settings:{heading:'Rooms across RainWood',propertyId:'',roomTypeIds:[],showPrices:true}}]}
 ];
 for(const page of standardPages){await p.sitePage.upsert({where:{tenantId_slug:{tenantId:tenant.id,slug:page.slug}},update:{themeId:theme.id,draftContent:{sections:page.sections},publishedContent:{sections:page.sections},status:'PUBLISHED'},create:{tenantId:tenant.id,themeId:theme.id,title:page.title,slug:page.slug,status:'PUBLISHED',draftContent:{sections:page.sections},publishedContent:{sections:page.sections},seo:{title:`${page.title} | RainWood Hotels`,description:`RainWood Hotels ${page.title.toLowerCase()}.`},navigation:[],publishedAt:new Date()}})}
 const media=[{tenantId:tenant.id,filename:'rainwood-aurum-exterior.jpg',url:images.aurum[0],mimeType:'image/jpeg',sizeBytes:0,altText:'RainWood Aurum exterior'},{tenantId:tenant.id,filename:'rainwood-room.jpg',url:images.aurum[1],mimeType:'image/jpeg',sizeBytes:0,altText:'RainWood premium room'}];
 for(const asset of media){const existing=await p.mediaAsset.findFirst({where:{tenantId:asset.tenantId,filename:asset.filename}});if(!existing) await p.mediaAsset.create({data:asset});}
 await p.user.update({where:{tenantId_email:{tenantId:tenant.id,email:adminEmail}},data:{passwordHash,status:'ACTIVE',role:'TENANT_ADMIN',name:'RainWood Admin'}});
 console.log({tenant:tenant.slug,seeded:true});
}
main().finally(()=>p.$disconnect());
